os: Visual Studio 2017
version: '{build}'
branches:
  except:
    - gh-pages
clone_depth: 10
build:
  verbosity: minimal
build_script:
  - ps: .\build.cmd BuildPackage
test: off
artifacts:
  - path: 'bin\*.nupkg'
    name: Gluon
